### ISSUE TITLE
waf是否有关键字拦截检测的功能呢？

### ISSUE THREAD

**Issue by Iceqaq** [Safe3/uuWAF#10]
例如  "赌博, AA,BB  这种敏感关键词汇"

**Comment by Safe3** [comment]
可以自己写规则，官网提供了高性能的多模匹配api，见https://waf.uusec.com/#/api/README?id=wafpmmatchsstrdict

**Comment by Safe3** [comment]
> 例如 "赌博, AA,BB 这种敏感关键词汇"

可以自己写规则，官网提供了高性能的多模匹配api，见https://waf.uusec.com/#/api/README?id=wafpmmatchsstrdict

**Comment by Iceqaq** [comment]
3q~
