### ISSUE TITLE
希望完善的功能：增加一个拦截IP的日志或者字段

### ISSUE THREAD

**Issue by ym2011** [Safe3/uuWAF#12]
1、日志管理-日志列表无法看到哪些IP被拦截了。
WAF的默认规则当中，是否命中了规则就会拦截。拦截的IP是哪些，拦截的时间等等，都无法从日志管理-日志列表看到。
首页-安全态势里面显示：今日拦截 IP 总数，但是也无法确定具体是哪些IP被拦截了。
2、日志管理-日志列表的字段是否能添加一个规则的ID字段。

**Comment by Safe3** [comment]
拦截的客户端ip在日志中是有的，日志中的第一栏就是对应的规则名称。
后续可以优化下展示，将规则详情展示在日志详情中
