### ISSUE TITLE
初始密码错误

### ISSUE THREAD

**Issue by BLkubin** [Safe3/uuWAF#15]
一键脚本安装后初始密码不正确，无法进入后台

**Comment by Safe3** [comment]
你得提供系统环境，一般出现这种情况的是没看网站说明，安装到了不支持的系统上

**Comment by Yoga7xm** [comment]
+1 
cenots7 一键安装之后，初始密码不正确，无法进入后台

**Comment by Safe3** [comment]
请加入官方群进一步讨论
