### ISSUE TITLE
增加对自定义HTTP头作为源IP的功能

### ISSUE THREAD

**Issue by f0re1gnKey** [Safe3/uuWAF#20]
X-Forward-For 在多层网关下，假如进行结构变更，要调整是第几个IP，麻烦，而且容易忘记，耦合程度较高

边界网关设置自定义HTTP头存放源IP，可以透传到下游所有的设备，希望uuwaf也支持自定义HTTP表头识别源IP

**Comment by Safe3** [comment]
采纳，择期加入

**Comment by LancelotLewis** [comment]
@Safe3 什么时候能加入这个功能啊

**Comment by Safe3** [comment]
> @Safe3 什么时候能加入这个功能啊

南墙v3.0.1版已经支持该功能
