### ISSUE TITLE
無法登入後台

### ISSUE THREAD

**Issue by redbean0721** [Safe3/uuWAF#21]
我不管是使用1panel或主機直接安裝(ubuntu 22.04)都無法使用帳號admin密碼wafadmin登入後台, 都顯示帳號或密碼錯誤

**Comment by Safe3** [comment]
可以加官方群给更多详情，帮你看看

**Comment by MiderWong** [comment]
如果修改了数据库配置，请参考：https://github.com/Safe3/uuWAF/issues/48#issuecomment-2044204817
