### ISSUE TITLE
需要添加LICENSE许可证

### ISSUE THREAD

**Issue by crudlll** [Safe3/uuWAF#25]
使用1Panel搭建个人服务的时候发现了这个免费Waf，非常感谢能提供这么好的项目，但是也有一些疑问：

**是否考虑添加相关LICENSE，明确一下用户的使用许可呢？**

比如声明社区版是否可以用于学习研究、个人网站使用或者商业用途？而哪些行为是所不允许的呢；
拥有明确的LICENSE不仅可以提高社区活跃、增加社区信任，促进开放合作和共享，也能维护你们的企业权益避免商业纠纷，都是一件好事。

**Comment by Safe3** [comment]
> 使用1Panel搭建个人服务的时候发现了这个免费Waf，非常感谢能提供这么好的项目，但是也有一些疑问：
> 
> **是否考虑添加相关LICENSE，明确一下用户的使用许可呢？**
> 
> 比如声明社区版是否可以用于学习研究、个人网站使用或者商业用途？而哪些行为是所不允许的呢； 拥有明确的LICENSE不仅可以提高社区活跃、增加社区信任，促进开放合作和共享，也能维护你们的企业权益避免商业纠纷，都是一件好事。

多谢提醒，目前社区版可以用于学习研究、个人或者企业网站使用，我们有时间补充LICENSE！好用的话麻烦给个star并多多宣传！

**Comment by Safe3** [comment]
已加
