### ISSUE TITLE
docker需要指定端口部署，80和443可自定义，因为有些项目需要指定端口访问达到安全性，但是还要加waf更安全

### ISSUE THREAD

**Issue by 357341051** [Safe3/uuWAF#27]
docker需要指定端口部署，80和443可自定义，因为有些项目需要指定端口访问达到安全性，但是还要加waf更安全
所以，需要用到waf，但目前waf是固定80和443端口，希望docker镜像部署能增加指定端口，谢谢

**Comment by Safe3** [comment]
> docker需要指定端口部署，80和443可自定义，因为有些项目需要指定端口访问达到安全性，但是还要加waf更安全 所以，需要用到waf，但目前waf是固定80和443端口，希望docker镜像部署能增加指定端口，谢谢

这个可以自行修改docker-compose.yml文件来自定义

**Comment by realstephenzhao** [comment]
希望能在安装防火墙时提供自定义端口功能。

我在使用 1Panel 时，WAF 与 服务器 （Nginx 以及 OpenLiteSpeed）端口冲突，与其修改惯用的服务器端口，不若在安装 uuWAF 提供修改端口的便利。

![](https://i.postimg.cc/zXjHmRMW/image.png)
