### ISSUE TITLE
欢迎红标如何删除

### ISSUE THREAD

**Issue by cyril-cheng** [Safe3/uuWAF#28]
![image](https://github.com/Safe3/uuWAF/assets/49748357/dfe5a073-d437-4e29-9c1e-50b97dd01c98)
我这强迫症，欢迎红标无法点掉，怎么办

**Comment by Safe3** [comment]
> ![image](https://user-images.githubusercontent.com/49748357/270164295-dfe5a073-d437-4e29-9c1e-50b97dd01c98.png) 我这强迫症，欢迎红标无法点掉，怎么办

不影响使用，后面版本再调整
