### ISSUE TITLE
安全态势 加入 按指定站点统计

### ISSUE THREAD

**Issue by qq8554650** [Safe3/uuWAF#3]
添加了很多站点，需要查看某个站点的态势
另外可加入按时间范围等其他条件查询

**Comment by Safe3** [comment]
@qq8554650 日志管理中已经有查询功能了，查看某个站点的态势建议用waf的kafka插件同步到Elasticsearch中，插件见https://github.com/Safe3/uuWAF/blob/main/plugins/kafka-logger.lua
