### ISSUE TITLE
uuwaf是不是无法使用cdn

### ISSUE THREAD

**Issue by zhumengsishen** [Safe3/uuWAF#31]
uuwaf是不是无法使用cdn

**Comment by Safe3** [comment]
CDN默认使用原站的缓存策略，原站没定义时使用自己设置的CDN规则，缓存是否成功可以根据返回的X-Waf-Cache http头来看

**Comment by 12123ads** [comment]
> CDN默认使用原站的缓存策略，原站没定义时使用自己设置的CDN规则，缓存是否成功可以根据返回的X-Waf-Cache http头来看

我想套cloudflare有办法吗？
