### ISSUE TITLE
There is an error in v3.0.1 when submitting the site configuration.

### ISSUE THREAD

**Issue by sertraline-echo** [Safe3/uuWAF#42]
**Describe the bug**
I set up the service using docker-compose, but I can't submit the website settings.

**Screenshots**
![image](https://github.com/Safe3/uuWAF/assets/116793559/51607fc5-2baa-45a4-9ab2-2648b9291acb)

**Comment by Safe3** [comment]
It seems the uuwaf process doesn't run,please gives us more information,such as os info and the /uuwaf/logs/error.log,so we can figure out the problem.
