### ISSUE TITLE
三个影响正常使用的小问题

### ISSUE THREAD

**Issue by yggcwx** [Safe3/uuWAF#50]
反馈几个在试用中发现的问题：
1.内存占用过高，望后续优化；
2.在三台机子上测试，都存在部署南墙后无法在1panel面板里申请证书的问题，停止南墙容器后申请会继续失败，卸载后就能正常申请；
3.部署南墙后，在1panel面板里建立的网站，即使没有在南墙里建立监测网站，也无法正常访问。

**Comment by Safe3** [comment]
后续版本南墙会加上自动获取免费证书和证书续期功能

**Comment by Safe3** [comment]
南墙v4.0.1已支持自动获取免费证书和证书续期功能
