### ISSUE TITLE
使用uuWAF代理uuWAF服务域名，“今日网站访问总数”数据异常

### ISSUE THREAD

**Issue by MiderWong** [Safe3/uuWAF#51]
**BUG描述**
使用uuWAF代理uuWAF服务域名，“今日网站访问总数”数据异常
[我不确定是否正确，只是作为一个疑点提出来]

**复现过程**
1、1Panel申请泛域名证书;
2、uuWAF导入证书;
3、添加uuWAF域名，上游地址:127.0.0.1:4443;
4、选中所有规则(新增官方提供的http强制转https的规则)，完成域名添加;
5、使用域名访问uuWAF,访问成功，默认进入“安全态势”菜单;
6、点击“站点管理”菜单，再点击“安全态势”菜单，会看到“今日网站访问总数”次数会一次增加7/8/9不等

**截图效果**
![初始数量](https://github.com/Safe3/uuWAF/assets/7487008/123b6a82-d053-4eeb-afdb-55efbffafd9a)
![访问站点管理](https://github.com/Safe3/uuWAF/assets/7487008/330bf9c0-62cb-463b-a7e4-a22cdc4fc63f)
![今日网站访问总数更新](https://github.com/Safe3/uuWAF/assets/7487008/b10165b3-f21a-4346-86ba-38400e6d9c2f)
![重复操作后总数更新](https://github.com/Safe3/uuWAF/assets/7487008/f324b8fc-c9fb-4394-be19-ea83143c7793)

**服务端系统环境:**
 - OS:  CentOS 9, Core 5.14
 - 安装方式：主机版安装
 - Version：社区版 v3.3.3

**客户端系统环境:**
 - OS: ArchLinux 2024.1, Core 6.8.4
 - Browser：Chrome 123.0.6312.105(latest)

**Comment by Safe3** [comment]
访问总数是指请求总数，ip是指有多少个ip访问网站，你理解错了

**Comment by MiderWong** [comment]
理解了，我以为“访问总数”统计的是网页页面访问次数。
