### ISSUE TITLE
3个问题.上游ip配置127.0.0.1  ,后台证书提示不安全.  站点配置 多个域名

### ISSUE THREAD

**Issue by 21307369** [Safe3/uuWAF#63]
1.环境是 1panel 在不暴露外部端口的情况下容器IP 是 127.0.0.1:端口的方式.  502 bad  换成容器ip 问题容器IP在docker重启后会改变Ip .
2.初次安装的时候登陆后台提示证书错误的问题,
3. www.xxx.com xxx.com  2个域名绑定一个站点的问题

**Comment by Safe3** [comment]
1、容器中127.0.0.1是容器自身，需要填主机ip
2、后台证书默认是自签名证书，需要自行替换/uuwaf/web/conf中的server.crt和server.key为你自己的证书
3、添加多个站点对应多个域名
