### ISSUE TITLE
试验pikachu靶场，对默认规则的修改建议

### ISSUE THREAD

**Issue by k4n5ha0** [Safe3/uuWAF#64]
我关闭“防持续攻击 累计攻击超过100次，则在10分钟内拦截该ip访问”这个规则后，sqlmap可以跑出注入
payload：
`id=3 AND GTID_SUBSET(CONCAT(0x716b706271,(SELECT MID((IFNULL(CAST(schema_name AS NCHAR),0x20)),1,190) FROM INFORMATION_SCHEMA.SCHEMATA LIMIT 0,1),0x716b7a7871),6646)`
对应上面的payload，响应包中应判断禁止存在：
`Malformed GTID set specification`

另外也验证建议：
将默认的SQL报错检测规则中
`if waf.status == 500 then`
这个判断改为
`if waf.respContentLength> 2  then`

当前waf版本：v4.4.1

**Comment by Safe3** [comment]
好的，确认这个没有拦截，谢谢你的建议！
