### ISSUE TITLE
试验pikachu靶场，对响应策略存在疑问

### ISSUE THREAD

**Issue by k4n5ha0** [Safe3/uuWAF#65]
![image](https://github.com/Safe3/uuWAF/assets/22064977/6806a893-bef6-4bd1-9627-27e9e1f72692)
如上图，响应包存在以下文本
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ']-(SELECT/**_**/0/**_**/WHERE/**_**/1028=1028/**_**/AND/**_**/6204=(SELECT/**_**' at line 1`
同时，我已经将“SQL报错检测”的默认策略改为响应包长度大于2如下图
![image](https://github.com/Safe3/uuWAF/assets/22064977/faad4021-cd8e-4036-8783-73db07aa9b00)

`You have an error in your SQL syntax(?: near|;)`该正则未正确判断响应包中敏感信息

再次建议将本策略改为兼容pikachu等等靶场的策略，以增加甲方采购前试用的竞争性

**Comment by Safe3** [comment]
确认是返回chunk编码页面没有处理，现已支持
