### ISSUE TITLE
docker安装下载不了镜像，用本主机安装出现报错提示。

### ISSUE THREAD

**Issue by cjqyxq** [Safe3/uuWAF#66]
[root@localhost opt]# curl https://waf.uusec.com/waf-install -o waf-install && sudo bash ./waf-install && rm -f ./waf-install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.4M  100 23.4M    0     0   174k      0  0:02:17  0:02:17 --:--:--  206k
         正在检查安装环境...
Last metadata expiration check: 0:23:53 ago on 2024年06月21日 星期五 15时38分04秒.
Dependencies resolved.
================================================================================
 Package           Architecture   Version                  Repository      Size
================================================================================
Installing:
 net-tools         x86_64         2.10-3.oe2203            update         200 k

Transaction Summary
================================================================================
Install  1 Package

Total download size: 200 k
Installed size: 881 k
Downloading Packages:
net-tools-2.10-3.oe2203.x86_64.rpm              1.9 MB/s | 200 kB     00:00    
--------------------------------------------------------------------------------
Total                                           1.9 MB/s | 200 kB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : net-tools-2.10-3.oe2203.x86_64                         1/1 
  Running scriptlet: net-tools-2.10-3.oe2203.x86_64                         1/1 
  Verifying        : net-tools-2.10-3.oe2203.x86_64                         1/1 

Installed:
  net-tools-2.10-3.oe2203.x86_64                                                

Complete!
         正在安装数据库...
         卸载旧版MySql...
Last metadata expiration check: 0:00:02 ago on 2024年06月21日 星期五 16时01分59秒.
jemalloc-3.6.0-1.el8.x86_64.rpm                  71 kB/s | 115 kB     00:01    
Dependencies resolved.
================================================================================
 Package         Architecture  Version                Repository           Size
================================================================================
Installing:
 jemalloc        x86_64        1:3.6.0-1.el8          @commandline        115 k

Transaction Summary
================================================================================
Install  1 Package

Total size: 115 k
Installed size: 339 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : jemalloc-1:3.6.0-1.el8.x86_64                          1/1 
  Running scriptlet: jemalloc-1:3.6.0-1.el8.x86_64                          1/1 
  Verifying        : jemalloc-1:3.6.0-1.el8.x86_64                          1/1 

Installed:
  jemalloc-1:3.6.0-1.el8.x86_64                                                 

Complete!
Last metadata expiration check: 0:00:05 ago on 2024年06月21日 星期五 16时01分59秒.
percona-icu-data-files-8.0.33-25.1.el8.x86_64.r 1.0 MB/s | 2.1 MB     00:01    
Dependencies resolved.
================================================================================
 Package                   Arch      Version              Repository       Size
================================================================================
Installing:
 percona-icu-data-files    x86_64    8.0.33-25.1.el8      @commandline    2.1 M

Transaction Summary
================================================================================
Install  1 Package

Total size: 2.1 M
Installed size: 3.3 M
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : percona-icu-data-files-8.0.33-25.1.el8.x86_64          1/1 
  Running scriptlet: percona-icu-data-files-8.0.33-25.1.el8.x86_64          1/1 
  Verifying        : percona-icu-data-files-8.0.33-25.1.el8.x86_64          1/1 

Installed:
  percona-icu-data-files-8.0.33-25.1.el8.x86_64                                 

Complete!
Last metadata expiration check: 0:00:08 ago on 2024年06月21日 星期五 16时01分59秒.
percona-server-shared-compat-8.0.33-25.1.el8.x8 1.6 MB/s | 1.2 MB     00:00    
Error: 
 Problem: 冲突的请求
  - nothing provides libcrypto.so.10()(64bit) needed by percona-server-shared-compat-8.0.33-25.1.el8.x86_64
  - nothing provides libcrypto.so.10(libcrypto.so.10)(64bit) needed by percona-server-shared-compat-8.0.33-25.1.el8.x86_64
  - nothing provides libssl.so.10()(64bit) needed by percona-server-shared-compat-8.0.33-25.1.el8.x86_64
  - nothing provides libssl.so.10(libssl.so.10)(64bit) needed by percona-server-shared-compat-8.0.33-25.1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Last metadata expiration check: 0:00:09 ago on 2024年06月21日 星期五 16时01分59秒.
percona-server-shared-8.0.33-25.1.el8.x86_64.rp 680 kB/s | 1.5 MB     00:02    
Error: 
 Problem: 冲突的请求
  - nothing provides percona-server-shared-compat needed by percona-server-shared-8.0.33-25.1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Last metadata expiration check: 0:00:12 ago on 2024年06月21日 星期五 16时01分59秒.
percona-server-client-8.0.33-25.1.el8.x86_64.rp 3.1 MB/s |  16 MB     00:05    
Error: 
 Problem: 冲突的请求
  - nothing provides libreadline.so.7()(64bit) needed by percona-server-client-8.0.33-25.1.el8.x86_64
  - nothing provides percona-server-shared needed by percona-server-client-8.0.33-25.1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Last metadata expiration check: 0:00:18 ago on 2024年06月21日 星期五 16时01分59秒.
percona-server-server-8.0.33-25.1.el8.x86_64.rp 3.1 MB/s |  86 MB     00:27    
Error: 
 Problem: 冲突的请求
  - nothing provides liblber-2.4.so.2()(64bit) needed by percona-server-server-8.0.33-25.1.el8.x86_64
  - nothing provides libldap_r-2.4.so.2()(64bit) needed by percona-server-server-8.0.33-25.1.el8.x86_64
  - nothing provides percona-server-client needed by percona-server-server-8.0.33-25.1.el8.x86_64
  - nothing provides percona-server-shared needed by percona-server-server-8.0.33-25.1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Last metadata expiration check: 0:00:46 ago on 2024年06月21日 星期五 16时01分59秒.
percona-server-rocksdb-8.0.33-25.1.el8.x86_64.r 2.5 MB/s |  14 MB     00:05    
Error: 
 Problem: 冲突的请求
  - nothing provides percona-server-client = 8.0.33-25.1.el8 needed by percona-server-rocksdb-8.0.33-25.1.el8.x86_64
  - nothing provides percona-server-server = 8.0.33-25.1.el8 needed by percona-server-rocksdb-8.0.33-25.1.el8.x86_64
  - nothing provides percona-server-shared = 8.0.33-25.1.el8 needed by percona-server-rocksdb-8.0.33-25.1.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[南墙] Percona MySQL数据库安装失败，请确保网络访问正常
请问如何安装？谢谢！

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [openeuler22.03-LTS]

**Comment by Safe3** [comment]
docker版因最近国内屏蔽了所有docker hub镜像，所以需要使用代理访问。
主机版现已更新兼容性更好的安装脚本，你可以再安装主机版南墙试试！

**Comment by cjqyxq** [comment]
请问用什么系统比较好？我用QQ群友说的AnolisOS8.9安装，仍然报数据库文件找不到的错误。提示如下：

[root@localhost ~]# curl https://waf.uusec.com/waf-install -o waf-install && sudo bash ./waf-install && rm -f ./waf-install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.4M  100 23.4M    0     0  1782k      0  0:00:13  0:00:13 --:--:-- 2524k
[南墙] 正在检查安装环境...
[南墙] 卸载旧版MySql...
[南墙] 正在安装数据库...
上次元数据过期检查：2:50:02 前，执行于 2024年06月23日 星期日 06时41分15秒。
percona-release-latest.noarch.rpm                              82 kB/s |  20 kB     00:00    
依赖关系解决。
==============================================================================================
 软件包                     架构              版本              仓库                     大小
==============================================================================================
安装:
 percona-release            noarch            1.0-27            @commandline             20 k

事务概要
==============================================================================================
安装  1 软件包

总计：20 k
安装大小：32 k
下载软件包：
运行事务检查
事务检查成功。
运行事务测试
事务测试成功。
运行事务
  准备中  :                                                                               1/1 
  安装    : percona-release-1.0-27.noarch                                                 1/1 
  运行脚本: percona-release-1.0-27.noarch                                                 1/1 
* Enabling the Percona Original repository
<*> All done!
* Enabling the Percona Release repository
<*> All done!
The percona-release package now contains a percona-release script that can enable additional repositories for our newer products.

For example, to enable the Percona Server 8.0 repository use:

  percona-release setup ps80

Note: To avoid conflicts with older product versions, the percona-release setup command may disable our original repository for some products.

For more information, please visit:
  https://www.percona.com/doc/percona-repo-config/percona-release.html


  验证    : percona-release-1.0-27.noarch                                                 1/1 

已安装:
  percona-release-1.0-27.noarch                                                               

完毕！
* Disabling all Percona Repositories
* Enabling the Percona Original repository
<*> All done!
* Enabling the Percona Tools repository
<*> All done!
AnolisOS-8 - AppStream                                         44 kB/s | 4.3 kB     00:00    
AnolisOS-8 - BaseOS                                            42 kB/s | 4.3 kB     00:00    
AnolisOS-8 - Extras                                            30 kB/s | 3.0 kB     00:00    
AnolisOS-8 - PowerTools                                        36 kB/s | 4.3 kB     00:00    
AnolisOS-8 - Kernel 5.10                                       43 kB/s | 4.3 kB     00:00    
Percona Release release/noarch YUM repository                 7.5 kB/s | 1.5 kB     00:00    
Percona Original release/x86_64 YUM repository                 15 kB/s | 2.9 kB     00:00    
Percona Tools release/x86_64 YUM repository                    15 kB/s | 2.9 kB     00:00    
元数据缓存已建立。
上次元数据过期检查：0:00:02 前，执行于 2024年06月23日 星期日 09时31分24秒。
所有的匹配结果均已经被参数的模块化过滤条件筛除: percona-server-server
错误：没有任何匹配: percona-server-server
上次元数据过期检查：0:00:04 前，执行于 2024年06月23日 星期日 09时31分24秒。
错误：
 问题: package percona-server-rocksdb-8.3.0-1.1.el8.x86_64 from ps-8x-innovation-release-x86_64 requires percona-server-shared = 8.3.0-1.1.el8, but none of the providers can be installed
  - 无法为该任务安装最佳候选
  - package percona-server-shared-8.3.0-1.1.el8.x86_64 from ps-8x-innovation-release-x86_64 is filtered out by modular filtering
(尝试添加 '--skip-broken' 来跳过无法安装的软件包 或 '--nobest' 来不只使用软件包的最佳候选)
[南墙] Percona MySQL安装失败，请确保网络访问正常
[root@localhost ~]# sudo yum install -y ca-certificates
上次元数据过期检查：0:01:53 前，执行于 2024年06月23日 星期日 09时31分24秒。
软件包 ca-certificates-2023.2.60_v7.0.306-80.0.an8.noarch 已安装。
依赖关系解决。
无需任何处理。
完毕！
[root@localhost ~]# curl https://waf.uusec.com/waf-install -o waf-install && sudo bash ./waf-install && rm -f ./waf-install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.4M  100 23.4M    0     0  1763k      0  0:00:13  0:00:13 --:--:-- 1985k
[南墙] 正在检查安装环境...
[南墙] 卸载旧版MySql...
[南墙] 正在安装数据库...
上次元数据过期检查：0:03:07 前，执行于 2024年06月23日 星期日 09时31分23秒。
percona-release-latest.noarch.rpm                              90 kB/s |  20 kB     00:00    
依赖关系解决。
==============================================================================================
 软件包                     架构              版本              仓库                     大小
==============================================================================================
安装:
 percona-release            noarch            1.0-27            @commandline             20 k

事务概要
==============================================================================================
安装  1 软件包

总计：20 k
安装大小：32 k
下载软件包：
运行事务检查
事务检查成功。
运行事务测试
事务测试成功。
运行事务
  准备中  :                                                                               1/1 
  安装    : percona-release-1.0-27.noarch                                                 1/1 
  运行脚本: percona-release-1.0-27.noarch                                                 1/1 
* Enabling the Percona Original repository
<*> All done!
* Enabling the Percona Release repository
<*> All done!
The percona-release package now contains a percona-release script that can enable additional repositories for our newer products.

For example, to enable the Percona Server 8.0 repository use:

  percona-release setup ps80

Note: To avoid conflicts with older product versions, the percona-release setup command may disable our original repository for some products.

For more information, please visit:
  https://www.percona.com/doc/percona-repo-config/percona-release.html


  验证    : percona-release-1.0-27.noarch                                                 1/1 

已安装:
  percona-release-1.0-27.noarch                                                               

完毕！
* Disabling all Percona Repositories
* Enabling the Percona Original repository
<*> All done!
* Enabling the Percona Tools repository
<*> All done!
AnolisOS-8 - AppStream                                         43 kB/s | 4.3 kB     00:00    
AnolisOS-8 - BaseOS                                            39 kB/s | 4.3 kB     00:00    
AnolisOS-8 - Extras                                            27 kB/s | 3.0 kB     00:00    
AnolisOS-8 - PowerTools                                        43 kB/s | 4.3 kB     00:00    
AnolisOS-8 - Kernel 5.10                                       46 kB/s | 4.3 kB     00:00    
Percona Release release/noarch YUM repository                 7.4 kB/s | 1.5 kB     00:00    
Percona Original release/x86_64 YUM repository                 15 kB/s | 2.9 kB     00:00    
Percona Tools release/x86_64 YUM repository                    13 kB/s | 2.9 kB     00:00    
元数据缓存已建立。
上次元数据过期检查：0:00:03 前，执行于 2024年06月23日 星期日 09时34分39秒。
所有的匹配结果均已经被参数的模块化过滤条件筛除: percona-server-server
错误：没有任何匹配: percona-server-server
上次元数据过期检查：0:00:04 前，执行于 2024年06月23日 星期日 09时34分39秒。
错误：
 问题: package percona-server-rocksdb-8.3.0-1.1.el8.x86_64 from ps-8x-innovation-release-x86_64 requires percona-server-shared = 8.3.0-1.1.el8, but none of the providers can be installed
  - 无法为该任务安装最佳候选
  - package percona-server-shared-8.3.0-1.1.el8.x86_64 from ps-8x-innovation-release-x86_64 is filtered out by modular filtering
(尝试添加 '--skip-broken' 来跳过无法安装的软件包 或 '--nobest' 来不只使用软件包的最佳候选)
[南墙] Percona MySQL安装失败，请确保网络访问正常

**Comment by cjqyxq** [comment]
后面用centos7.5版本安装成功。先用上学习先。谢谢！

**Comment by Safe3** [comment]
还可以试试Rocky Linux、AlmaLinux，应该是可以安装的

**Comment by cjqyxq** [comment]
> 还可以试试Rocky Linux、AlmaLinux，应该是可以安装的

好的，谢谢！
