### ISSUE TITLE
請問是否能回應自定義http code以及更改預設返回頁面

### ISSUE THREAD

**Issue by redbean0721** [Safe3/uuWAF#68]
![image](https://github.com/Safe3/uuWAF/assets/102888458/01599b16-ab21-49c3-8d05-e7256e2750a3)

**Comment by Safe3** [comment]
可以在站点管理中自定义拦截页面

**Comment by redbean0721** [comment]
請問自定義攔截畫面該怎麼使用, 以及能否讓其回應除403以外狀態碼

**Comment by Safe3** [comment]
暂不支持
