### ISSUE TITLE
一个小的用户体验的建议

### ISSUE THREAD

**Issue by k4n5ha0** [Safe3/uuWAF#69]
在规则管理搜索时支持无视大小写，否则会让人以为不支持XSS防护
![image](https://github.com/Safe3/uuWAF/assets/22064977/834cc126-1f4d-46f1-96a4-98936b803ddf)
![image](https://github.com/Safe3/uuWAF/assets/22064977/6033fb1f-2ba1-4cc3-af99-e7c23659d6a1)

**Comment by Safe3** [comment]
good

**Comment by Safe3** [comment]
有的用户需要区分大小写，暂不变更
