### ISSUE TITLE
官方文档缺少checkXSS函数的介绍

### ISSUE THREAD

**Issue by k4n5ha0** [Safe3/uuWAF#70]
如下图
![image](https://github.com/Safe3/uuWAF/assets/22064977/05cf4ae1-7410-4385-8218-757f737cb575)
![image](https://github.com/Safe3/uuWAF/assets/22064977/0e1a16f3-74d8-4228-8aba-0eabae8afb8b)

**Comment by Safe3** [comment]
good

**Comment by Safe3** [comment]
文档已更新，谢谢！
