### ISSUE TITLE
一些bad case的增补

### ISSUE THREAD

**Issue by k4n5ha0** [Safe3/uuWAF#73]
sqlmap1.8  最新版uuwaf   checkSQLI(v, 3)
-----------分割线---------
![image](https://github.com/Safe3/uuWAF/assets/22064977/446062d2-2d26-438b-902e-6a90e08d3600)
`2;(SELECT * FROM (SELECT(SLEEP(5)))kJcs)#`
-----------分割线---------
![image](https://github.com/Safe3/uuWAF/assets/22064977/4b5f7368-d5cc-42bd-970b-ff53b44111d0)
`2" AND 3489=RAISE_ERROR(CHR(55)||CHR(48)||CHR(48)||CHR(48)||CHR(49),CHR(113)||CHR(118)||CHR(106)||CHR(106)||CHR(113)||(SELECT (CASE WHEN (3489=3489) THEN 1 ELSE 0 END) FROM SYSIBM.SYSDUMMY1)||CHR(113)||CHR(113)||CHR(112)||CHR(118)||CHR(113)) AND "HyGT" LIKE "HyGT`
-----------分割线---------
![image](https://github.com/Safe3/uuWAF/assets/22064977/e40e93bf-e925-468f-928d-7f51c5ef937a)
`-8255)) OR CASE WHEN 7703=5079 THEN 7703 ELSE JSON(CHAR(104,83,112,112)) END AND ((4702=4702`
-----------分割线---------
应当在AST语义引擎中，禁用SQL的json、RAISE_ERROR、SLEEP函数，如出现多个chr函数也应当拦截

**Comment by Safe3** [comment]
收到，谢谢反馈！
