### ISSUE TITLE
如何卸载呢？没有找到相关的配置说明~

### ISSUE THREAD

**Issue by Iceqaq** [Safe3/uuWAF#9]
没有找到相关的配置说明

**Comment by Safe3** [comment]
ps -ax | grep waf-service | awk '{print $1}' | xargs kill -9 > /dev/null 2>&1
ps -ax | grep uuwaf | awk '{print $1}' | xargs kill -9 > /dev/null 2>&1
/uuwaf/waf-service -s uninstall > /dev/null 2>&1
rm -rf /uuwaf
