### ISSUE TITLE
SSL证书自动申请似乎会引发对服务器的渗透攻击

### ISSUE THREAD

**Issue by CreeperLKF** [Safe3/uuWAF#97]
**Describe the bug**
全新安装的uuWAF，在站点管理中新建站点并且不配置证书，在对某个站点进行初次的时候，会同步引发攻击，而如果使用自己的证书或者是用HTTP连接则不会触发攻击。
根据[排查](https://www.elpsylkf.work/p/security-problem-with-auto-ssl-in-waf/)可能是ACME申请证书时候出现的问题，但还不知道更深的原因，也不知道是WAF用的脚本问题，或是证书提供方的问题，或是服务器受到了中间人攻击之类的。

**To Reproduce**
1. Fresh install uuWAF;
2. Deploy a website without ssl configured (using auto-ssl);
3. Access the website;
4. Checkout the defense log and find attack trials immediately after access.

**Screenshots**
Please refer to [my blog](https://www.elpsylkf.work/p/security-problem-with-auto-ssl-in-waf/). The access time and attack time are highly aligned.
<img width="326" alt="5af1b1ababa75cf06d977b362519dbb" src="https://github.com/user-attachments/assets/1187ecab-dc94-481c-af5d-f211295865ca">

**Comment by Safe3** [comment]
这就是很普通的网上一些自动扫描的工具扫描产生的记录，和ssl证书没任何关系。一些互联网上的攻击爬虫会定期对新解析的域名进行自动扫描

**Comment by CreeperLKF** [comment]
> 这就是很普通的网上一些自动扫描的工具扫描产生的记录，和ssl证书没任何关系。一些互联网上的攻击爬虫会定期对新解析的域名进行自动扫描

好吧，感谢。在用WAF之前没注意到这个攻击和访问记录有关，因此有些担忧。文件验证的方式要走HTTP，可能是中间哪个设备监听了这种流量，不过我们也改变不了什么了。
